server:
  port: 8761
spring:
  application:
    name: provider-user-service
eureka:
  client:
    service-url:
      defaultZone: http://10.0.72.79:8761/eureka/
  instance:
    prefer-ip-address: true
