drop table jcy_order;
CREATE TABLE `jcy_order` (
  `id` bigint(20) NOT NULL,
  `pid` varchar(32) DEFAULT NULL COMMENT '父订单id',
  `order_no` varchar(32) NOT NULL COMMENT '订单号',
  `user_no` varchar(32) NOT NULL COMMENT '用户id',
  `pay_user_no` varchar(32) DEFAULT NULL COMMENT '支付人id',
  `merchnat_user_no` varchar(32) DEFAULT NULL COMMENT '商家id',
  `merchant_user_name` varchar(64) DEFAULT NULL COMMENT '商家名',
  `merchnat_user_logo` varchar(255) DEFAULT NULL COMMENT '商家图标',
  `amount` decimal(10,2) DEFAULT NULL COMMENT '实付金额',
  `order_amount` decimal(10,2) NOT NULL COMMENT '订单金额',
  `discount_amount` decimal(10,2) DEFAULT NULL COMMENT '优惠金额',
  `del_flag` tinyint(4) DEFAULT '0' COMMENT '订单删除状态0:正常 1：删除',
  `platform` tinyint(4) NOT NULL COMMENT '创建订单的平台',
  `order_status` tinyint(4) NOT NULL COMMENT '订单状态',
  `order_type` tinyint(4) NOT NULL COMMENT '订单类型',
  `order_desc` varchar(1024) COLLATE utf8mb4  DEFAULT NULL COMMENT '订单描述',
  `pay_no` varchar(64) DEFAULT NULL COMMENT '支付订单号',
  `pay_status` tinyint(4) NOT NULL COMMENT '支付状态',
  `pay_type` varchar(32) DEFAULT NULL COMMENT '支付方式',
  `pay_time` datetime DEFAULT NULL COMMENT '支付时间',
  `sent_status` tinyint(4) DEFAULT NULL COMMENT '发货状态：1已发货 2未发货\n',
  `sent_time` datetime DEFAULT NULL COMMENT '发货时间',
  `receive_status` tinyint(4) DEFAULT NULL COMMENT '收货状态',
  `receive_time` datetime DEFAULT NULL COMMENT '收货确认时间',
  `goods_amount` decimal(10,2) DEFAULT NULL COMMENT '商品金额',
  `freight_amount` decimal(10,2) DEFAULT NULL COMMENT '运费',
  `packing_amount` decimal(10,2) DEFAULT NULL COMMENT '包装费',
  `date_created` datetime DEFAULT NULL COMMENT '创建时间',
  `last_updated` datetime DEFAULT NULL COMMENT '修改时间',
  `proxy_pay_no` varchar(32) DEFAULT NULL COMMENT '代付人ID',
  `proxy_pay_status` tinyint(4) DEFAULT NULL COMMENT '代付状态',
  `merchnat_tel` varchar(32) DEFAULT NULL COMMENT '商家联系电话',
  `refund_amount` decimal(10,0) DEFAULT '0' COMMENT '退款金额',
  `refund_status` tinyint(4) DEFAULT '0' COMMENT '订单退款状态0:初始状态，1；退款中，2；退款成功',
  `event_type` varchar(32) DEFAULT NULL COMMENT '操作类型',
  `timestamp` datetime  DEFAULT NULL COMMENT '时间戳'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


drop table jcy_order_goods_snapshot;
create table jcy_order_goods_snapshot(
  id bigint(20) NOT NULL,
  order_no varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '订单号',
  goods_no varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '商品号',
  img varchar(200) COLLATE utf8_bin DEFAULT NULL,
  name varchar(32) COLLATE utf8_bin DEFAULT NULL,
  num int(11) DEFAULT NULL,
  price  decimal(10,2) DEFAULT NULL,
  scale  varchar(32) COLLATE utf8_bin DEFAULT NULL,
  snapshot_amount decimal(10,2) DEFAULT NULL,
  snapshot_count int(11) DEFAULT NULL,
  snapshot_goods_id  varchar(32) COLLATE utf8_bin DEFAULT NULL,
  snapshot_order_type int(11) DEFAULT NULL,
  snapshot_platform int(11) DEFAULT NULL,
  snapshot_user_no  varchar(32) COLLATE utf8_bin DEFAULT NULL,
  snapshot_book_dates  varchar(200) COLLATE utf8_bin DEFAULT NULL,
  snapshot_cost decimal(10,2) DEFAULT NULL,
  snapshot_default_flag int(11) DEFAULT NULL,
  snapshot_jcb_num decimal(10,2) DEFAULT NULL,
  snapshot_recharge_id  varchar(32) COLLATE utf8_bin DEFAULT NULL,
  date_created  datetime  DEFAULT NULL,
  last_updated  datetime  DEFAULT NULL,
  `event_type` varchar(32) DEFAULT NULL COMMENT '操作类型',
  `timestamp` datetime  DEFAULT NULL COMMENT '时间戳'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

drop table jcy_order_address_snapshot;
create table jcy_order_address_snapshot (
  id bigint(20) NOT NULL,
  order_no varchar(32) COLLATE utf8_bin DEFAULT NULL COMMENT '订单号',
  company varchar(32) COLLATE utf8_bin DEFAULT NULL ,
  date_created datetime DEFAULT NULL ,
  depart  varchar(32) DEFAULT NULL ,
  floor  varchar(32) DEFAULT NULL ,
  member  varchar(32) DEFAULT NULL ,
  name  varchar(32) DEFAULT NULL ,
  phone  varchar(32) DEFAULT NULL ,
  user_no  varchar(32) DEFAULT NULL ,
  area varchar(32) DEFAULT NULL  ,
  city  varchar(32) DEFAULT NULL ,
  detail  varchar(32) DEFAULT NULL ,
  mobile  varchar(32) DEFAULT NULL ,
  province  varchar(32) DEFAULT NULL ,
  user_name  varchar(32) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
